### ISSUE TITLE
Feature Request: publish to F-Droid

### ISSUE THREAD

**Issue by kmogged** [twofas/2fas-android#14]
Some people have Android (or Linux) devices that are unable to use the Google Play Store or choose not to use the Google Play Store. I spent a quick minute understanding F-Droid submissions (I am not a mobile developer) https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

It looks like it involves a pull request with the metadata and a recipe for building. After that F-Droid builds the application from source.

My main use case is that I have a faulty phone with the 2fas app and now it's in a failed boot loop, so I need to be able to load another device with the application, but I don't have Play Store or App Store as an option.

**Comment by 2fas-com** [comment]
We'll be working on developing our app for F-Droid, but not in the near future because we have other priorities right now. So stay tuned and we hope you'll remain patient!

**Comment by ety001** [comment]
Hope add F-Droid support.

**Comment by shuvashish76** [comment]
> We'll be working on developing our app for F-Droid, but not in the near future because we have other priorities right now.

No worries take your time but please keep the issue open ;)

**Comment by UlyssesZh** [comment]
Why is this issue closed as completed? I do not see 2FAS on F-droid.

**Comment by aadityabhatia** [comment]
The issue is certainly not resolved. You do not "develop for F-Droid" but rather follow their procedure for publishing to their store, which is fairly straight forward. From what I understand, it does involve removing non-open third party code (e.g. tracking libraries), which makes the process complex for certain projects. Not sure whether that's the case here.

Curious to learn what is holding it up the process and how the community can help move forward. But at any rate, the issue is not resolved and should be either left open or closed with "won't fix".

**Comment by rafakob** [comment]
It's not that straight forward. We're using Google's FCM for push notifications when app is paired with our desktop browser extension. F-Droid won't accept it - that's pretty much the only limitation (plus Crashlytics but we could live without it).

We would have to maintain two different builds and implement some other push provider (on mobile and on backend) or hide the browser extension feature completely on F-Droid variant. Right now we have some other priorities and instead of F-Droid we've started to publish the APK on the GitHub release page (for people who do not have Google Play).

I agree that we should have a "won't fix" label.

**Comment by UlyssesZh** [comment]
Google's push service shouldn't have been used in the first place. UnifiedPush is better.

**Comment by aadityabhatia** [comment]
Not using Google's push library has significant battery implications if I understand correctly, so maintaining two builds is understandable. I'd acknowledge that it is tedious to deal with that. Thank you for being transparent about it!
