### ISSUE TITLE
bug: 2FAS seems to create an invisible overlay that keeps me from tapping anywhere

### ISSUE THREAD

**Issue by RonnyAL** [twofas/2fas-android#166]
### Bug type

Error at runtime

### App version

5.4.6

### Device environment

Android 14
Samsung Galaxy S23 Ultra 

### Bug description

**Description**
This error state seems to involve what I described in the title. I am unable to scroll, tap buttons, etc., but I see the 2FA timers count down, so the app is otherwise running normally, it seems.

I've found a way to exit out of the app - by double pressing the power button to open the camera app. However, the issue persists there (screen is still nonresponsive). The only way to get out of this, as far as I know, is to tap the power button to turn off the screen and leave it off for a while (a few minutes probably). Next time I turn it back on, this is fixed.

Sometimes I can scroll a little in the 2FAS app, but it's very slow and choppy, and it eventually stops completely with the issue described above.

**Steps to reproduce**
It's a little unclear exactly how this happens. I thought it might be related to the biometric authentication screen, but I've tried canceling this and authenticating via PIN, which leads to the same problem. There's no lag or unresponsiveness in the PIN entry screen.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I understand that security vulnerabilities should be reported to security@2fas.com instead of on GitHub.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by s3rious0** [comment]
Hey @RonnyAL,

thank you for opening this issue.

I have checked the App with the same Android ( 14 ) and App Version ( 5.4.6 ).

On my Device, I haven't the errors do you describe. I think it's an problem with your device or the source of the Installation of the app.

The following questions are interesting to know:

- Is the problem came on a specific Version of the app, or was it forever so?

- Who you have installed the app? Play store or GitHub APK?

- Have you tried to clear the storage and the cache? 
**IMPORTANT: When you clear the cache and the storage, all 2FAS Keys are deleted. Please create an backup before you do this step. **

When the points are not helpfulness, you can try to reinstall the app. 
**IMPORTANT: Too here, when you reinstall the app, all 2FAS Keys are deleted. Please create a backup before you do this step.**

Please let me know, if this steps works or not.

More Details, you can become from the following Google Website: 

https://support.google.com/android/answer/2668665?hl=de

Thank you.

Greetings.

**Comment by RonnyAL** [comment]
Thanks for the reply, @s3rious0. The problem has only occurred this once, but has since passed. You're probably right that it was not related to the app itself, but I figured I'd open an issue anyway since whatever caused the problem didn't seem to affect anything else.

In any case, the problem is gone now, so the issue can be closed.

**Comment by s3rious0** [comment]
Hey @RonnyAL,

thanks for your answer. 

So that you are the creator of this Issue, is it possible that you can close this ticket?

Thank you.

Greetings.
